# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCar',
            new_name='ProductDetail',
        ),
    ]
